# Render deployment configuration for HumanDNS
services:
  # Backend API Service
  - type: web
    name: humandns-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: humandns-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: '["https://humandns-frontend.onrender.com"]'
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
    autoDeploy: true
    branch: main

  # Frontend Service
  - type: web
    name: humandns-frontend
    env: static
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://humandns-backend.onrender.com
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main

databases:
  # PostgreSQL Database
  - name: humandns-db
    plan: free
    databaseName: humandns
    user: humandns
