"""add_oauth_fields

Revision ID: d4f8e9a2b3c1
Revises: ec9efd63dbdd
Create Date: 2025-01-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f8e9a2b3c1'
down_revision = 'ec9efd63dbdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make password_hash nullable for OAuth users
    op.alter_column('users', 'password_hash',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True)
    
    # Add OAuth provider fields
    op.add_column('users', sa.Column('google_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('github_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('discord_id', sa.String(length=100), nullable=True))
    
    # Create indexes for OAuth fields
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    
    # Drop OAuth columns
    op.drop_column('users', 'discord_id')
    op.drop_column('users', 'github_id')
    op.drop_column('users', 'google_id')
    
    # Make password_hash not nullable again
    op.alter_column('users', 'password_hash',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=False)
    # ### end Alembic commands ###

